Svg
open-dollar/od-contracts pull request #115
Opened 2023-09-14 14:34 UTC by daopunk

need to finish visual, but it renders

2023-09-14 23:49 UTC, pi0neerpat requested changes

2023-09-14 23:49 UTC, pi0neerpat commented on src/contracts/proxies/Vault721.sol
> +    '{"name": "Open Dollar Vaults","description": "Tradable Vaults for the Open Dollar stablecoin protocol. Caution! Trading this NFT means trading the ownership of your Vault in the Open Dollar prot
image and externalLink need "https://" protocol

2023-09-14 23:49 UTC, pi0neerpat commented on parts.txt
Delete this file

2023-09-15 00:57 UTC, pi0neerpat reviewed
Looks good! Lets deploy

2023-09-15 05:54 UTC, pi0neerpat requested changes
1. Variable names in `GoerliContracts.s.sol` have been modified. Is this the new naming schema? I updated my script `prepareForSdk.js` in another branch, and if you think there will be additional changes, let me know.
2. Please delete the old  `GoerliContracts-2.s.sol`. Its confusing to have it here. If you'd like to save these, they should be placed elsewhere and labeled by timestamp.
3. In `GoerliContracts.s.sol`, please add the missing values for these contracts:
- WETH address
- FTRG address
- PROXY_BASIC_ACTIONS
- PROXY_GLOBAL_SETTLEMENT_ACTIONS
4. `yarn build` is failing due to the changes mentioned in item 1 above, specifically in how the contracts are used in `GoerliDeployment.sol`

2023-09-20 16:40 UTC, daopunk commented
solves #82

2023-09-20 19:30 UTC, pi0neerpat approved these changes

2023-09-20 19:32 UTC, merged