Issue #169: Forge docs formatting
open-dollar/od-contracts pull request #178
Opened 2023-10-11 01:34 UTC by jahabeebs

Closes #169 

## Description
- I mentioned in the previous PR there's an issue on mobile when opening the sidebar but I was able to work around this
- sidebar opens and closes on mobile and desktop
- the sidebar is hidden by default to avoid content being blocked on mobile when getting to page (it's inevitable the sidebar will block the content but I think the the main problem in the issue is that previously we couldn't close the sidebar)
- code snippets won't overlap sidebar (had to change z-index)

## Screnshots

Mobile

https://github.com/open-dollar/od-contracts/assets/47253537/d8a982bb-9c2f-48b8-8921-564a5345bb1d

Desktop

https://github.com/open-dollar/od-contracts/assets/47253537/f8dc3bd7-c7e8-4cc7-9f08-679c218938bf

Responsive

https://github.com/open-dollar/od-contracts/assets/47253537/84cc5c6d-a4ff-4127-832a-fd325ef324ab

2023-10-13 23:03 UTC, pi0neerpat requested changes
How are you testing this?

I'm running `./build-docs.sh` and then `mdbook serve`

but I don see the sidebar 

![image](https://github.com/open-dollar/od-contracts/assets/35622595/08688419-7e5c-438f-abd1-6c047369d693)

Also, I think the sidebar should be open by default, and stay open, so the user can easily see where they are in the document (similar to this behavior https://hai-private-k5wttpr3x-hai-on-op.vercel.app/). I prefer Desktop be the best experience over mobile.

2023-10-13 23:32 UTC, jahabeebs commented
> How are you testing this?
> 
> I'm running `./build-docs.sh` and then `mdbook serve`
> 
> but I don see the sidebar
> 
> ![image](https://user-images.githubusercontent.com/35622595/275078708-08688419-7e5c-438f-abd1-6c047369d693.png)
> 
> Also, I think the sidebar should be open by default, and stay open, so the user can easily see where they are in the document (similar to this behavior https://hai-private-k5wttpr3x-hai-on-op.vercel.app/). I prefer Desktop be the best experience over mobile.

@pi0neerpat I've used the same commands to build & serve and I'm testing on firefox and chrome desktop. What browser are you using? I can't reproduce the invisible sidebar thing.

As far as the sidebar staying open by default, the https://hai-private-k5wttpr3x-hai-on-op.vercel.app/ link you posted actually keeps the sidebar closed by default on my iPhone. What device and browser are you using? If we try to always keep the sidebar open on an iPhone it will look like this: 

<img width="441" alt="Screenshot 2023-10-13 at 6 27 57 PM" src="https://github.com/open-dollar/od-contracts/assets/47253537/9d303a33-c7ac-4f48-a5aa-ca514f460a03">

and then the user will have to move the sidebar out of the way by doing this (see photo below):

why not allow the sidebar to collapse instead? there are mobile nav buttons on each side of the screen on mobile for page to page navigation and the sidebar can be toggled via the hamburger menu

<img width="428" alt="Screenshot 2023-10-13 at 6 28 10 PM" src="https://github.com/open-dollar/od-contracts/assets/47253537/e3ab17a3-f686-4406-9ae1-a7d38e46f69c">

2023-10-16 19:09 UTC, jahabeebs commented
@pi0neerpat 

I've just added some logic to hide the sidebar by default on mobile but it show it by default on desktop. I used 1080 as the screen cut off but if you think it should be smaller I can reduce it. Maybe you can test in incognito/private browsing mode (so no caching issues) on the screen that was giving you weird errors before? 

default hidden on mobile

https://github.com/open-dollar/od-contracts/assets/47253537/c4b1196f-a3e8-4bc2-bca4-f93c0d808b09

default shown on desktop

https://github.com/open-dollar/od-contracts/assets/47253537/547c2ed3-70a0-4951-a4f8-be62c3b9f6b3

2023-10-17 17:40 UTC, pi0neerpat approved these changes

2023-10-17 19:01 UTC, merged