add missing debt check
open-dollar/od-contracts pull request #253
Opened 2023-11-27 18:38 UTC by 0xdavinchee

closes #240 

- we do a check after `_settleDebt` in `AccountingEngine.auctionDebt` to ensure that a debt auction cannot be created without bad debt

2023-11-27 22:27 UTC, daopunk requested changes
instead of checking twice with 
`if (_params.debtAuctionBidSize > _unqueuedUnauctionedDebt(_debtBalance)) revert AccEng_InsufficientDebt();`
you can move the check from before settle debt to after settle debt

HAI reference for same fix: https://github.com/hai-on-op/core/pull/15/files#diff-7a40a76cb31a577a91d6480dd147f30a16e11137dc2da045eb7e6ba5e5535b64

2023-11-29 20:23 UTC, 0xdavinchee commented
> instead of checking twice with `if (_params.debtAuctionBidSize > _unqueuedUnauctionedDebt(_debtBalance)) revert AccEng_InsufficientDebt();` you can move the check from before settle debt to after settle debt
> 
> HAI reference for same fix: https://github.com/hai-on-op/core/pull/15/files#diff-7a40a76cb31a577a91d6480dd147f30a16e11137dc2da045eb7e6ba5e5535b64

suggestion addressed

2023-11-29 21:47 UTC, daopunk approved these changes

2023-11-30 16:39 UTC, pi0neerpat commented
Please merge when ready

2023-11-30 18:58 UTC, merged

2023-11-30 19:33 UTC, daopunk commented
@0xdavinchee also, remember to delete branch after successfully merged