fix: surplus auction creation
open-dollar/od-contracts pull request #254
Opened 2023-11-27 21:47 UTC by Sabnock01

Resolves #214 
* Updates the `AccountingEngine.sol` at lines [#L213](https://github.com/open-dollar/od-contracts/blob/6023a38154c87d0974a3d9fce0e47bfba7057f37/src/contracts/AccountingEngine.sol#L213) and [#L215](https://github.com/open-dollar/od-contracts/blob/6023a38154c87d0974a3d9fce0e47bfba7057f37/src/contracts/AccountingEngine.sol#L215) to use `WAD` instead of `ONE_HUNDRED_WAD` according the the submission recommendation to correct the issue of surplus auctions being created with `_amountToSell` 100x larger than it should be.

2023-11-27 22:45 UTC, St4rgarden commented
So it’s not incorrect per se. In order for the calculations to be correct - we do in fact need to replace 100 WAD with 1 WAD…

But it was concerning to me that this issue was flagged, but not the missing conversion of RAD to WAD from the SafeEngine.  So that tells me the security audit was never completed.

2023-11-27 23:06 UTC, Sabnock01 commented
> So it’s not incorrect per se. In order for the calculations to be correct - we do in fact need to replace 100 WAD with 1 WAD…
> 
> But it was concerning to me that this issue was flagged, but not the missing conversion of RAD to WAD from the SafeEngine.  So that tells me the security audit was never completed.

Interesting. Thanks for the context.

2023-11-28 19:21 UTC, pi0neerpat requested changes
Before the value is sent to SafeEngine, we must convert from WAD to RAD

2023-12-11 19:38 UTC, pi0neerpat approved these changes

2023-12-11 19:39 UTC, pi0neerpat commented
As explained in #254, there is no need to convert

2023-12-11 19:39 UTC, merged