Closed #159
open-dollar/od-contracts pull request #269
Opened 2023-12-04 11:14 UTC by St4rgarden

Simple fix for targeting a potentially wrong safe for transfer collateral and debt.

2023-12-06 15:34 UTC, daopunk commented
after you change PR to dev branch, you can request a review from Patrick and/or me so we know the PR is ready for review

2023-12-07 22:28 UTC, daopunk requested changes
merge branch to dev

2023-12-08 05:01 UTC, St4rgarden commented
@daopunk Ahh thanks for letting me know that; I was wondering why some of my PRs were acting weird.

Okay I have changed to merge on dev and correctly linked this pr to the issue.

2023-12-11 19:12 UTC, pi0neerpat approved these changes

2023-12-15 20:44 UTC, daopunk approved these changes

2023-12-16 06:04 UTC, merged