Handlercan nonce fix
open-dollar/od-contracts pull request #347
Opened 2024-01-07 21:45 UTC by 0xdavinchee

closes #219 
similar to #346 - review #346 first and close to see the actual changeset in this one

Which means it has the same issue mentioned in #346.

`handlerExists` can be removed in favor of `safeHandlerToSafeId`, as long as this invariant holds true: safeId is never 0 for any safe handlers, then `handlerExists` if `safeHandlerToSafeId != 0`.

2024-01-09 02:02 UTC, pi0neerpat approved these changes
> handlerExists can be removed in favor of safeHandlerToSafeId, as long as this invariant holds true: safeId is never 0 for any safe handlers, then handlerExists if safeHandlerToSafeId != 0.

I believe safeId will never be 0, so we could remove it. Will defer to @cupOJoseph on if we should.

2024-01-09 15:10 UTC, pi0neerpat requested changes
From @cupOJoseph:

> If you're confident in the safe usage of safeID then I would support removing the redundancy

Lets go ahead and remove it then.

2024-01-09 20:19 UTC, 0xdavinchee commented
> From @cupOJoseph:
> 
> > If you're confident in the safe usage of safeID then I would support removing the redundancy
> 
> Lets go ahead and remove it then.

done :)

2024-01-10 13:58 UTC, pi0neerpat approved these changes

2024-01-12 14:31 UTC, merged