accounting engine test fixes; no longer transfer extra surplus method
open-dollar/od-contracts pull request #402
Opened 2024-01-25 11:40 UTC by St4rgarden

Closes #303 

Removed all tests specifically tied to the deprecated method `transferExtraSurplus` as that method no longer exists.  Fixed the other two tests which were impacted by the change from `transferExtraSurplus` to `extraSurplusReceiver` and surplus splitting.

Recommend adding additional tests for the changed functionality and new revert statements.

2024-01-26 18:03 UTC, daopunk requested changes
Yes, agree with your recommendation, can you add more tests for the new functionality.

2024-01-26 22:17 UTC, pi0neerpat approved these changes

2024-01-29 18:45 UTC, daopunk commented
@St4rgarden checking on the status here?

2024-01-31 05:58 UTC, St4rgarden commented
> @St4rgarden checking on the status here?

Yeah the requested changes above are not supported by ds-test.  There is no `assertFalse` method there.  This looks ready to merge.

2024-01-31 21:56 UTC, pi0neerpat commented
Closing as transferred to @MrDeadCe11

2024-01-31 21:56 UTC, closed without merging