Fix: codesize validation
open-dollar/od-contracts pull request #479
Opened 2024-02-09 02:16 UTC by fabiohild

2024-02-09 21:02 UTC, daopunk requested changes

2024-02-09 23:19 UTC, fabiohild commented on test/testnet/utils/HaiTest.t.sol
> +    (, address _msgSender,) = vm.readCallers();
Need to update the lib forge-std to the latest sir:
`forge update lib/forge-std`

2024-02-09 23:22 UTC, fabiohild commented on test/testnet/utils/HaiTest.t.sol
> +    (, address _msgSender,) = vm.readCallers();
I updated it already, if you delete the lib folder and compile it should pull the latest

2024-02-13 16:53 UTC, daopunk approved these changes

2024-02-13 16:54 UTC, merged