Replace Hash-Based State with Value-Based State
open-dollar/od-contracts pull request #601
Opened 2024-04-06 03:47 UTC by daopunk

closes #534 
closes #600 

Notice:
Due to the limitations of overriding the `tokenURI` function, specifically that it is a non-state changing view function that only returns a string, it is not possible to use it as a means of updating state information about NFVs. So the pattern of updating NFV states via applicable function calls from the ODSafeManager is maintained.

DOS attacks are reverted using a value-based state check that enforces no change or desirable changes value of the NFV after token transfer. Furthermore, the logic to look up the values in the SafeEngine has been added to the Vault721, so that it is not routing that call through the NFTRenderer contract, removing the NFTRenderer from state enforcement.

2024-04-06 05:11 UTC, daopunk commented
TokenCollateral, which should and will most likely be zero is the last attribute, positioned away from the Collateral attribute to avoid confusion.

![Screenshot 2024-04-05 at 10 10 02 PM](https://github.com/open-dollar/od-contracts/assets/50965054/47bdfa77-fccf-447a-98bd-9f4a0ea3a0f3)

2024-04-06 06:26 UTC, daopunk commented
@pi0neerpat need to fix/change tests for this PR, but you can at least review the contract changes. I can write the tests tomorrow, before I forget.

2024-04-06 14:12 UTC, pi0neerpat requested changes

2024-04-06 14:12 UTC, pi0neerpat commented on src/contracts/proxies/Vault721.sol
> +    if (_collateralNow < _nfv.collateral || _debtNow > _nfv.debt) revert StateViolation();
Pending discussion

2024-04-06 14:12 UTC, pi0neerpat commented on src/contracts/proxies/NFTRenderer.sol
> +      '"},{"trait_type":"TokenCollateral","value":"',
I think we should rename to "Internal Collateral" to be even more explicit

2024-04-07 05:05 UTC, daopunk commented
![Screenshot 2024-04-06 at 10 05 23 PM](https://github.com/open-dollar/od-contracts/assets/50965054/557af862-578c-46f5-bae8-e56410314394)

2024-04-07 05:06 UTC, daopunk commented
TokenURI is printing with all data, and non-formatted nums

2024-04-07 06:33 UTC, daopunk commented
@MrDeadCe11 requesting help to finish some mocked unit tests in Vault721.t.sol that I commented out, since I am off.

2024-04-08 21:36 UTC, MrDeadCe11 commented
merged with pr #602 to include other updates to vault721, modify parameters and even emission improvements.

2024-04-09 02:15 UTC, MrDeadCe11 commented on src/contracts/proxies/Vault721.sol
> +    if (_collateralNow < _nfv.collateral || _debtNow > _nfv.debt) revert StateViolation();
did this get resolved?

2024-04-09 16:27 UTC, pi0neerpat requested changes

2024-04-09 16:27 UTC, pi0neerpat commented on src/contracts/proxies/ODSafeManager.sol
> +    vault721.updateNfvState(_safe);
We may need to add a check here to only updateNfvState if the value is decreased, to avoid DoS

2024-04-09 20:40 UTC, pi0neerpat approved these changes

2024-04-09 20:42 UTC, merged