immutable owner
open-dollar/od-contracts pull request #78
Opened 2023-08-23 15:11 UTC by daopunk

`setOwner` from Ownable is not used anywhere in protocol. There is another `setOwner` function from an Auth contract, which is used in testing.

solves #76 
solves #71 
solves #24 
solves #23

2023-08-25 17:33 UTC, cupOJoseph commented
What happened to

`function safeManager() external returns (address);` in IVault721.sol? 

should that be part of this? otherwise looks good.

2023-08-25 17:33 UTC, cupOJoseph approved these changes

2023-08-25 17:35 UTC, cupOJoseph requested changes
please fix compile errors and double check nothing was left behind since #75 was closed

2023-08-25 17:52 UTC, daopunk commented
`function safeManager() external returns (address);` in IVault721.sol?

^not needed if Proxy is non-transferrable

2023-08-30 20:04 UTC, cupOJoseph approved these changes

2023-08-30 20:16 UTC, merged